// app/profile/privacy.tsx
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { SUPPORT_EMAIL } from '../../constants/contact';

const C = {
  bg:'#0A0A0F', surface:'#13131A', border:'#2A2A38',
  primary:'#F5A623', primaryMuted:'rgba(245,166,35,0.12)',
  textPrimary:'#F0F0F5', textSecondary:'#9090A8', textTertiary:'#5A5A70',
};
const SP = { 2:8,3:12,4:16,5:20,6:24,8:32,10:40 } as const;
const R  = { md:10,lg:16 } as const;
const TY = { xs:11,sm:13,base:15,md:17 } as const;

// Mirrors the website policy (app/privacy/page.tsx in the website repo)
// word for word, including its DRAFT status. Change both together.
const SECTIONS: { title: string; body?: string; bullets?: string[] }[] = [
  {
    title: '1. Information We Collect',
    body: 'We collect information you provide directly and information generated by using the platform, including:',
    bullets: [
      'Account information — name, email address, phone number, and password;',
      'Approximate location, used to match customers with nearby contractors and show relevant search results;',
      'Job details you submit — trade needed, description, address, preferred dates;',
      'Photos and documents you upload — job photos, and, for contractors, license/insurance/ID documents submitted for verification;',
      'Payment information — handled entirely by our third-party payment processor. Tradease does not store your full card number; we retain only the limited billing metadata (such as a masked card summary or transaction ID) the processor returns to us;',
      "Messages sent through the platform's in-app chat, and basic usage data (device, app version, log data).",
    ],
  },
  {
    title: '2. How We Use Your Information',
    body: 'We use the information above to:',
    bullets: [
      'Match customers with relevant, nearby contractors and vice versa;',
      'Enable communication between matched customers and contractors;',
      'Operate, maintain, and secure the platform, including fraud prevention and account verification;',
      'Process payments and send transactional and account-related notifications;',
      'Respond to support requests and legal obligations.',
    ],
  },
  {
    title: '3. How We Share Your Information',
    body: 'We do not sell your personal information. We share it only in these circumstances:',
    bullets: [
      'With the customer or contractor you are matched with, to the extent needed to complete a job (e.g. name, job address, contact details, uploaded photos);',
      'With infrastructure and service providers that operate the platform on our behalf — hosting and database (Supabase), email delivery, mapping/geolocation services, and payment processing — under agreements limiting their use of your data to providing that service;',
      'When required by law, subpoena, or to protect the safety of our users or the public.',
    ],
  },
  {
    title: '4. Data Retention',
    body: 'We retain account and job data for as long as your account is active and for a limited period afterward to satisfy legal, tax, dispute-resolution, and security obligations. When you delete your account, we delete or anonymize personal information that is no longer required to be kept, subject to those obligations.',
  },
  {
    title: '5. Your Rights',
    body: 'You can, at any time:',
    bullets: [
      'Access and update most of your account information directly in Settings;',
      'Request deletion of your account and associated data using the in-app “Delete Account” option in Settings → Privacy, which submits a deletion request that our team processes;',
      'Contact us with any other privacy request or question (see below).',
    ],
  },
  {
    title: '6. Security',
    body: 'We use industry-standard safeguards — encryption in transit, access controls, and row-level database security — to protect your information. No system is perfectly secure, and we encourage you to use a strong, unique password.',
  },
  {
    title: '7. Changes to This Policy',
    body: 'We may update this Privacy Policy as Tradease evolves. Material changes will be reflected on this page with an updated date above.',
  },
  {
    title: '8. Contact Us',
    body: `For any privacy question or request, email ${SUPPORT_EMAIL}.`,
  },
];

export default function PrivacyScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={s.container} edges={['top']}>
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)')} style={s.backBtn}>
          <Ionicons name="chevron-back" size={22} color={C.textPrimary} />
        </TouchableOpacity>
        <Text style={s.headerTitle}>Privacy Policy</Text>
        <View style={{ width:36 }} />
      </View>

      <ScrollView style={s.scroll} contentContainerStyle={s.scrollContent} showsVerticalScrollIndicator={false}>

        <View style={s.effectiveCard}>
          <Ionicons name="shield-checkmark-outline" size={18} color={C.primary} />
          <View>
            <Text style={s.effectiveLabel}>Last Updated</Text>
            <Text style={s.effectiveDate}>August 2026</Text>
          </View>
        </View>

        <View style={s.draftCard}>
          <Text style={s.draftText}>
            DRAFT — pending legal review, not final. This page is placeholder policy text
            published so users have something real to read while our attorney finalizes the
            binding version. It is not yet legally reviewed and may change.
          </Text>
        </View>

        {SECTIONS.map(sec => (
          <View key={sec.title} style={s.section}>
            <Text style={s.sectionTitle}>{sec.title}</Text>
            {sec.body && <Text style={s.sectionBody}>{sec.body}</Text>}
            {sec.bullets?.map(b => (
              <Text key={b} style={[s.sectionBody, s.bullet]}>{'\u2022  '}{b}</Text>
            ))}
          </View>
        ))}

        <View style={s.footer}>
          <Text style={s.footerText}>Questions about your privacy?</Text>
          <TouchableOpacity onPress={() => Linking.openURL(`mailto:${SUPPORT_EMAIL}`)}>
            <Text style={s.footerLink}>{SUPPORT_EMAIL}</Text>
          </TouchableOpacity>
        </View>

        <View style={{ height:SP[10] }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  container:      { flex:1, backgroundColor:C.bg },
  header:         { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingHorizontal:SP[4], paddingVertical:SP[3], borderBottomWidth:0.5, borderBottomColor:C.border },
  backBtn:        { width:36, height:36, alignItems:'center', justifyContent:'center' },
  headerTitle:    { fontSize:TY.md, fontWeight:'700', color:C.textPrimary, letterSpacing:-0.3 },
  scroll:         { flex:1 },
  scrollContent:  { paddingHorizontal:SP[5], paddingTop:SP[4] },
  effectiveCard:  { flexDirection:'row', alignItems:'center', gap:SP[3], backgroundColor:C.surface, borderRadius:R.lg, borderWidth:0.5, borderColor:C.border, padding:SP[4], marginBottom:SP[5] },
  effectiveLabel: { fontSize:TY.xs, color:C.textTertiary, fontWeight:'600', textTransform:'uppercase', letterSpacing:0.5 },
  effectiveDate:  { fontSize:TY.base, color:C.textPrimary, fontWeight:'700', marginTop:2 },
  draftCard:      { backgroundColor:'rgba(255,98,0,0.08)', borderRadius:R.md, borderWidth:1, borderColor:'rgba(255,98,0,0.3)', padding:SP[4], marginBottom:SP[6] },
  draftText:      { fontSize:TY.sm, color:'#FF6200', fontWeight:'700', lineHeight:20 },
  bullet:         { marginTop:SP[2], paddingLeft:SP[2] },
  section:        { marginBottom:SP[6] },
  sectionTitle:   { fontSize:TY.base, fontWeight:'700', color:C.primary, marginBottom:SP[3] },
  sectionBody:    { fontSize:TY.sm, color:C.textSecondary, lineHeight:22 },
  footer:         { backgroundColor:C.surface, borderRadius:R.lg, padding:SP[5], marginTop:SP[4], borderWidth:0.5, borderColor:C.border, alignItems:'center', gap:SP[2] },
  footerText:     { fontSize:TY.sm, color:C.textSecondary },
  footerLink:     { fontSize:TY.sm, color:C.primary, fontWeight:'700' },
});